# Development Docker Compose configuration file for TweetCheck

django:
  extends:
    file: docker-compose/common.yml
    service: django
  build: .
  command: "gunicorn -c config/gunicorn_config.py --reload wsgi:application"
  links:
    - db:postgres
    - redis
  volumes:
    - .:/usr/src/app

celery:
  extends:
    file: docker-compose/common.yml
    service: celery
  build: .
  links:
    - db:postgres
    - redis
  volumes:
    - .:/usr/src/app

data:
  extends:
    file: docker-compose/common.yml
    service: data

db:
  extends:
    file: docker-compose/common.yml
    service: db
  volumes_from:
    - data

redis:
  extends:
    file: docker-compose/common.yml
    service: redis

node:
  extends:
    file: docker-compose/common.yml
    service: node
  build: ../tweetcheck-node
  links:
    - redis
  volumes:
    - ../tweetcheck-node:/usr/src/app

angular:
  extends:
    file: docker-compose/common.yml
    service: angular
  build: ../tweetcheck-angular
  volumes:
    - ../tweetcheck-angular:/usr/src/app

nginx:
  extends:
    file: docker-compose/common.yml
    service: nginx
  build: ../tweetcheck-nginx
  command: bash -c 'rm /usr/share/nginx/html/dashboard && ln -s /usr/src/app/app /usr/share/nginx/html/dashboard && nginx -g "daemon off;"'
  ports:
    - "8000:80"
    - "8001:443"
  links:
    - django:gunicorn
    - node
  volumes_from:
    - angular
  volumes:
    - ../tweetcheck-nginx/nginx.conf:/etc/nginx/nginx.conf
