# Production Docker Compose configuration file for TweetCheck

django:
  image: atbaker/tweetcheck
  links:
    - db:postgres
    - redis
  env_file:
    - .env

celery:
  image: atbaker/tweetcheck
  working_dir: "/usr/src/app/tweetcheck"
  command: "celery -A config worker --loglevel=info"
  links:
    - db:postgres
    - redis
  env_file:
    - .env
  environment:
    C_FORCE_ROOT: "true"

data:
  image: postgres:9.4
  command: echo "Data-only container"

db:
  image: postgres:9.4
  volumes_from:
    - data

redis:
  image: redis:2.8

node:
  image: atbaker/tweetcheck-node
  links:
    - redis

nginx:
  image: atbaker/tweetcheck-angular
  ports:
    - "80:80"
    - "443:443"
  links:
    - django:gunicorn
    - node
