# Development Docker Compose configuration file for TweetCheck

django:
  build: .
  command: "gunicorn -c tweetcheck/config/gunicorn_config.py --reload wsgi:application"
  links:
    - db:postgres
    - redis
  env_file:
    - .env
  volumes:
    - .:/usr/src/app

celery:
  image: tweetcheck_django:latest
  working_dir: "/usr/src/app/tweetcheck"
  command: "celery -A config worker --loglevel=info"
  links:
    - db:postgres
    - redis
  env_file:
    - .env
  environment:
    C_FORCE_ROOT: "true"
  volumes:
    - .:/usr/src/app

data:
  image: postgres:9.4
  command: echo "Data-only container"

db:
  image: postgres:9.4
  volumes_from:
    - data

redis:
  image: redis:2.8

node:
  build: ../tweetcheck-node
  links:
    - redis
  volumes:
    - "../tweetcheck-node:/usr/src/app"

nginx:
  build: ../tweetcheck-angular
  volumes:
    - ../tweetcheck-angular:/usr/share/nginx/html
    - ../tweetcheck-angular/conf/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - "8000:80"
    - "8001:443"
  links:
    - django:gunicorn
    - node
