# Test Docker Compose configuration file for TweetCheck

django:
  build: .
  command: "gunicorn -c tweetcheck/config/gunicorn_config.py --reload wsgi:application"
  links:
    - db:postgres
    - redis:redis
  volumes:
    - .:/usr/src/app

celery:
  image: tweetcheck_django:latest
  working_dir: "/usr/src/app/tweetcheck"
  command: "celery -A config worker --loglevel=info"
  links:
    - db:postgres
    - redis:redis
  environment:
    C_FORCE_ROOT: "true"

data:
  image: postgres:9.4
  command: echo "Data-only container"

db:
  image: postgres:9.4
  volumes_from:
    - data

redis:
  image: redis:2.8

node:
  image: atbaker/tweetcheck-node
  links:
    - redis:redis

nginx:
  image: atbaker/tweetcheck-angular
  ports:
    - "80:80"
    - "443:443"
  links:
    - django:gunicorn
    - node:node

# Docker-compose test configuration file for TweetCheck

django:
  build: .
  links:
    - db:postgres
    - redis
  volumes:
    - .:/usr/src/app

celery:
  image: tweetcheck_django:latest
  working_dir: "/usr/src/app/tweetcheck"
  command: "celery -A config worker --loglevel=info"
  links:
    - db:postgres
    - redis
  environment:
    C_FORCE_ROOT: "true"
  volumes:
    - .:/usr/src/app

data:
  image: postgres:9.4
  command: echo "Data-only container"

db:
  image: postgres:9.4
  volumes_from:
    - data

redis:
  image: redis:2.8

node:
  image: atbaker/tweetcheck-node
  links:
    - redis

nginx:
  image: atbaker/tweetcheck-angular
  links:
    - django:gunicorn
    - node
