# Development Docker Compose configuration file for TweetCheck

django:
  image: atbaker/tweetcheck
  # build: .
  # command: "gunicorn -c tweetcheck/config/gunicorn_config.py --reload wsgi:application"
  # links:
  #   - db:postgres
  #   - redis
  env_file:
    - ../.env

celery:
  image: atbaker/tweetcheck
  command: "celery -A config worker --loglevel=info"
  # links:
  #   - db:postgres
  #   - redis
  env_file:
    - ../.env

data:
  image: postgres:9.4
  command: echo "Data-only container"

db:
  image: postgres:9.4
  # volumes_from:
  #   - data

redis:
  image: redis:2.8

node:
  image: atbaker/tweetcheck-node
  # build: ../tweetcheck-node
  # links:
  #   - redis
  # volumes:
  #   - "../tweetcheck-node:/usr/src/app"

angular:
  image: atbaker/tweetcheck-angular
  # build: ../tweetcheck-angular
  # volumes:
  #   - ../tweetcheck-angular:/usr/src/app

nginx:
  # build: ../tweetcheck-nginx
  image: atbaker/tweetcheck-nginx
  # command: bash -c 'rm /usr/share/nginx/html/dashboard && ln -s /usr/src/app/app /usr/share/nginx/html/dashboard && nginx -g "daemon off;"'
  # volumes_from:
  #   - angular
  # volumes:
  #   - ../tweetcheck-nginx/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - "80:80"
    - "443:443"
  # links:
  #   - django:gunicorn
  #   - node
