# Common Docker Compose configuration file for TweetCheck
# See https://docs.docker.com/compose/extends/ for more info

django:
  image: atbaker/tweetcheck
  env_file:
    - ../.env

celery:
  image: atbaker/tweetcheck
  command: "celery -A config worker --loglevel=info"
  env_file:
    - ../.env

data:
  image: postgres:9.4
  command: echo "Data-only container"

db:
  image: postgres:9.4

redis:
  image: redis:2.8

node:
  image: atbaker/tweetcheck-node

angular:
  image: atbaker/tweetcheck-angular

nginx:
  image: atbaker/tweetcheck-nginx
  ports:
    - "80:80"
    - "443:443"
